### PR TITLE
Refactoring

### PR DESCRIPTION
**Pull request by kassane**
Hi @suirad,

This research and experiment aims at cross-compile portability for C and C++ project (unified ABI)

**TODO:**
*  [x] replace libc with libzig when allocating resources or simply create a custom (basic) allocator in C++.
*  [ ] ~~experiment c++20 modules based on [this test](https://gist.github.com/kassane/7e9a2da137e13eb6e1dbab726693bdb7)~~ (don't work - rejected multi-objects win/macos)
* [ ] ~~to remove libc, need recreate `_start` entry point.~~ (broken ABI - zig has libc++abi or fully libc++ support only?)

### CODE REVIEW

**Comment by kassane** [comment]
## Current

Don't run on Windows, only Linux & MacOS. (zig version: 0.11.0-dev.1825+25b83188d)

@marler8997, has there ever been anything like this?

```bash
Matheus@DESKTOP-BUHRSIO UCRT64 ~/c-plus-minus
$ zig build run -freference-trace
The following command exited with code 5 (expected exited with code 0):
cd C:\msys64\home\Matheus\c-plus-minus && C:\msys64\home\Matheus\c-plus-minus\zig-out\bin\example.exe
error: UnexpectedExit
C:\Users\Matheus\Downloads\zig\master\files\lib\std\Build\RunStep.zig:424:9: 0x7ff68eb1a980 in runCommand (build.exe.obj)
        return error.UnexpectedExit;
        ^
C:\Users\Matheus\Downloads\zig\master\files\lib\std\Build\RunStep.zig:290:5: 0x7ff68eafd163 in make (build.exe.obj)
    try runCommand(
    ^
C:\Users\Matheus\Downloads\zig\master\files\lib\std\Build\Step.zig:75:5: 0x7ff68ea6a74d in make (build.exe.obj)
    try self.makeFn(self);
    ^
C:\Users\Matheus\Downloads\zig\master\files\lib\std\Build.zig:763:5: 0x7ff68ea57735 in makeOneStep (build.exe.obj)
    try s.make();
    ^
C:\Users\Matheus\Downloads\zig\master\files\lib\std\Build.zig:757:13: 0x7ff68ea576e1 in makeOneStep (build.exe.obj)
            return err;
            ^
C:\Users\Matheus\Downloads\zig\master\files\lib\std\Build.zig:718:9: 0x7ff68ea57479 in make (build.exe.obj)
        try self.makeOneStep(s);
        ^
C:\Users\Matheus\Downloads\zig\master\files\lib\build_runner.zig:259:21: 0x7ff68ea5aa74 in main (build.exe.obj)
            else => return err,
                    ^
error: the following build command failed with exit code 1:
C:\msys64\home\Matheus\c-plus-minus\zig-cache\o\8292045b8ed9203ff73fd449b80d17ad\build.exe C:\Users\Matheus\Downloads\zig\master\files\zig.exe C:\msys64\home\Matheus\c-plus-minus C:\msys64\home\Matheus\c-plus-minus\zig-cache C:\Users\Matheus\AppData\Local\zig run -freference-trace -freference-trace
```

**Comment by suirad** [comment]
@kassane this looks great so far. Looking forward to where you end up with it and will happily merge.

**Comment by kassane** [comment]
I am having trouble creating multiple objects containing each step of the module on Windows and MacOS.
Zig build gives the same error:
```bash
# MacOS target
error: macho does not support linking multiple objects into one
# Windows target
error: coff does not support linking multiple objects into one
```
Linux need hack (`ld.lld`) bug: `unclose quotes` to generate `pcm` file! Maybe `b.addSystemCommand` solve...

**Comment by kassane** [comment]
@suirad,
It is quite complicated to attend the module steps as a third party command line.
I will need to do further research on what happened in windows that is unavailable for now.

If you think the current state already helps, you can merge if you like.

**Comment by suirad** [comment]
Are there upstream Zig issues to track the blockers you faced when working on this?

**Comment by kassane** [comment]
> Are there upstream Zig issues to track the blockers you faced when working on this?

@suirad,

Windows case I didn't find anything about it and on Linux, zig is not responsible for the module `*.pcm` error, is `ld.lld` only, any other linker (`ld`, `zld`, `ld-linker`) works. https://github.com/llvm/llvm-project/issues/61198

About Windows segfault, performe some tests:
main-branch project before merge, ok on Windows.
My allocator in an isolated way, also worked.
https://cpp.godbolt.org/z/MMee3cz8z
I really didn't understand about Zig/MinGW (I don't have msvc installed).

It is interesting to open an isse about it. But before that if you can perform some more tests I would add.
Well, today is enough for me, I worked on it without a break for more than 5 hours.

**Pull request merged**
